<?php
/**
 * The base configurations of WordPress.
 *
 * This file has the following configurations: MySQL settings, Table Prefix,
 * Secret Keys, WordPress Language, and ABSPATH. You can find more information
 * by visiting {@link http://codex.wordpress.org/Editing_wp-config.php Editing
 * wp-config.php} Codex page. You can get the MySQL settings from your web host.
 *
 * Generated by the NerdPress WP-Config Generator
 * Wed, 19 Mar 2014 23:13:53 -0500
 *
 * Standard WordPress installation
 * Sandbox environment
 *
 * @author  Tom Jenkins <tom@thejenkinsweb.com>
 * @package WordPress
 */

/**
 * Home & site URL.
 *
 * This will override the home/site URL settings
 * in the General Settings of wp-admin.
 */
define('WP_HOME', 'http://nerd.dev');
define('WP_SITEURL', WP_HOME);

/**
 * MySQL settings.
 *
 * Update these to match the values necessary for
 * accessing the database.
 */
// Database name
define('DB_NAME', 'database');

// Database username
define('DB_USER', 'username');

// Database password
define('DB_PASSWORD', 'password');

// Database host (usually 'localhost')
define('DB_HOST', 'localhost');

// Database character set
define('DB_CHARSET', 'utf8');

// The database collation. Leave this blank unless otherwise required.
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY',         'H Lk!UJY2Ht?$xqHAq]X2J-<T76 uW7n-gmg4;0*cAjd#-*g *t8Qame0fk$^8EG');
define('SECURE_AUTH_KEY',  'tn|N%Y!F:uc2x$Mne9mdg8Sa;0G;n]-C;+Og?;6#t(+-BM]l.K-IJ?U5SW5 2z8;');
define('LOGGED_IN_KEY',    'Hj1D@|t1Vm#;`hsE2%CENDGwJIa&>C=`7rCTa1mPM+}p6!|SE<|l;lp_2$]!|a^~');
define('NONCE_KEY',        ')ykR&o*c&k(4iAQ3my_3y#kf2_7?M+dtDq!_U74^LRxED]Oj%dV0l^{sSO8^wE!~');
define('AUTH_SALT',        'H))^4$c92;s5Cf-ogO uGG;ApJZZirZ92OY#Z3cU)O~o`J2V*|L0(Px|<|d36)oG');
define('SECURE_AUTH_SALT', 'NP2=5b5coH#WVAu0]qn$BP+koP<(hbY!bwW-moKzIx4`R<hrB%g@mU{HEsR$/5 F');
define('LOGGED_IN_SALT',   '=Z.1z5+g+A%)luQTyA?sYX}G[233$,?& 2{L_C(r]TH-lN,)b=t#(,7(rp*BMw2|');
define('NONCE_SALT',       '18n>U*e$S+tfj>5$b+NkRV92*eh3Ts8#h0.m{t(+9NWOg7nsh]b~4cs_CP-u#CU@');
/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each a unique
 * prefix. Only numbers, letters, and underscores please!
 */
$table_prefix  = 'nrdwp_';

/**
 * WordPress Localized Language, defaults to English.
 *
 * Change this to localize WordPress.  A corresponding MO file for the chosen
 * language must be installed to wp-content/languages. For example, install
 * de.mo to wp-content/languages and set WPLANG to 'de' to enable German
 * language support.
 */
define('WPLANG', '');

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 */
define('WP_DEBUG', true);

/**
 * Content directory and URL.
 *
 * For WordPress installations using SVN externals and keeping the
 * content directory separate from WordPress core code.
 */
define('WP_CONTENT_DIR', dirname(__FILE__) . '/wp-content');
define('WP_CONTENT_URL', 'http://nerd.dev/wp-content');

/**
 * Admin cookie path.
 *
 * A path must be defined for the WordPress login cookie because
 * WordPress core is located in a subdirectory of the site.
 */
define('ADMIN_COOKIE_PATH', '/');

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if (! defined('ABSPATH'))
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
